/********************************************************************
* MyTreeMaker_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MyTreeMaker_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMyTreeMaker_Dict();
extern void G__cpp_setup_inheritanceMyTreeMaker_Dict();
extern void G__cpp_setup_typetableMyTreeMaker_Dict();
extern void G__cpp_setup_memvarMyTreeMaker_Dict();
extern void G__cpp_setup_globalMyTreeMaker_Dict();
extern void G__cpp_setup_memfuncMyTreeMaker_Dict();
extern void G__cpp_setup_funcMyTreeMaker_Dict();
extern void G__set_cpp_environmentMyTreeMaker_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MyTreeMaker.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MyTreeMaker_DictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__MyTreeMaker_DictLN_string;
extern G__linked_taginfo G__MyTreeMaker_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MyTreeMaker_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyTreeMaker_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MyTreeMaker_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MyTreeMaker_DictLN_Fun4AllBase;
extern G__linked_taginfo G__MyTreeMaker_DictLN_PHCompositeNode;
extern G__linked_taginfo G__MyTreeMaker_DictLN_SubsysReco;
extern G__linked_taginfo G__MyTreeMaker_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MyTreeMaker_DictLN_TTree;
extern G__linked_taginfo G__MyTreeMaker_DictLN_TFile;
extern G__linked_taginfo G__MyTreeMaker_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__MyTreeMaker_DictLN_PHG4Particle;
extern G__linked_taginfo G__MyTreeMaker_DictLN_HepMC;
extern G__linked_taginfo G__MyTreeMaker_DictLN_HepMCcLcLGenParticle;
extern G__linked_taginfo G__MyTreeMaker_DictLN_MyTreeMaker;
extern G__linked_taginfo G__MyTreeMaker_DictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__MyTreeMaker_DictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
